### ISSUE TITLE
路过，提个问题

### ISSUE THREAD

**Issue by Tarhyru** [normalHamal/DEW-club#3]
首先，不打算找个地方部署展示一下么...?
其次...这个项目结构是自己想的还是参照哪里的..
最近接手了一个项目结构和这个非常像...
其实，我个人对这种分层思想不是很了解...所以如果有参照的源头的话，想去看看

**Comment by normalHamal** [comment]
@Tarhyru 这个其实是一个已经很乱的东西了，又杂又没啥技术含量，所以没打算展示了，这个项目的结构的话是参照的[nodeclub](https://github.com/cnodejs/nodeclub/)，就是一个之前比赛的一个小模块，准备之后删库跑路了哈哈。
